In [2]:
# Ensure you have the following installed:
# numpy
# os
# compas
# compas_fd
# warnings
# traceback
# pickle

# Install by running:
# !pip install -r requirements.txt

In [3]:
import compas_fd

In [4]:
import numpy as np
import pickle
import pandas as pd

# G-code generation codes are cloned from https://github.com/tibor-barsi/GcodeGenerator. Tibor Barsi is the author of the code, and was a PhD student at the Ladisk lab of the University of Ljubljana
#  We should be careful with crediting the author of the code, if we ever want to make these code public.
from src.g_code_generation_copy.gcode_generator import G_code_generator
from src.g_code_generation_copy.tool_changer_functions import save_params, load_params, printer_start, load_tool, unload_tool, tool_change, take_photo, play_sound, printer_stop
# from src.additional_functions import *
from src.network import Network_custom, replace_brackets
import os

BYU_UW_root = r"G:\.shortcut-targets-by-id\1k1B8zPb3T8H7y6x0irFZnzzmfQPHMRPx\Illimited Lab Projects\Research Projects\Spiders\BYU-UW"

### Step 1: Define the network

In [5]:
# # Note that the coordinates of the vertices will change after equilibrium is reached.
# vertices    = np.array([[-10, 0, 0], [-5, 0,0], [0, 0, 0], [5, 0, 0], [10, 0, 0], [0,-10,0], [0,-5,0], [0,5,0], [0,10,0]])*10  # The coordinates of the vertices in mm
# edges       = [[0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [6, 2], [2, 7], [7, 8], [1, 6], [6, 3], [3, 7], [7,1]]                  # The edges of the network.
# paths       = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]   # 3D printable paths. Ensure an edge is not flipped.
# directions  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]          # Flip the curvature of an edge by setting the direction to -1.

# scalar = 80
# q_ring      = .5
# q_connectors = .8
# q_center    = .2
# q           = np.array([q_connectors, q_center, q_center, q_connectors, q_connectors, q_center, q_center, q_connectors, q_ring, q_ring, q_ring, q_ring])/scalar
# q[2]        = 1.5/scalar
# q[-1]        = 1.5/scalar
# fixed       = [0, 4, 5, 8]
# # model_name  = 'VS_ring{}_connectors{}_center{}_as{}'.format(q_ring, q_connectors, q_center, q[2]*scalar)
# model_name  = 'VS_ring{}_connectors{}_center{}_as{}_asr{}_s{}'.format(q_ring, q_connectors, q_center, q[2]*scalar, q[-1]*scalar, scalar)

# Create the network
# net = Network_custom.from_fd(vertices, edges, q, fixed, paths = paths, dir = directions)
model_name = "validation_unit_fstudy_1.15"
net = Network_custom.load_network(os.path.join(BYU_UW_root, 'networks', model_name + '.pkl'))
# The topology of structure is fixed after generation, but you can update force densities after making the network
# q[0] = .10
# net.update_shape(q)

# Plot the network like this
net.net_plot(color=True, elables = True, vlabels = False)

import matplotlib.pyplot as plt
cmap = plt.get_cmap('viridis')

# Convert to TikZ RGB format
f_plot = (net.f - np.min(net.f)) / (np.max(net.f) - np.min(net.f))
for val in f_plot:
    r, g, b, _ = cmap(val)  # Get RGBA (ignore A)color={rgb,1:red,0.282;green,0.141;blue,0.458}
    print("\draw[thick, color = {" + f"rgb,1:red,{r:.3f}; green,{g:.3f};blue, {b:.3f}"+"}];")

np.min(net.f), np.max(net.f)

<>:36: SyntaxWarning: invalid escape sequence '\d'
<>:36: SyntaxWarning: invalid escape sequence '\d'
C:\Users\thijs\AppData\Local\Temp\ipykernel_22136\731534389.py:36: SyntaxWarning: invalid escape sequence '\d'
  print("\draw[thick, color = {" + f"rgb,1:red,{r:.3f}; green,{g:.3f};blue, {b:.3f}"+"}];")


\draw[thick, color = {rgb,1:red,0.710; green,0.869;blue, 0.169}];
\draw[thick, color = {rgb,1:red,0.282; green,0.090;blue, 0.412}];
\draw[thick, color = {rgb,1:red,0.282; green,0.095;blue, 0.417}];
\draw[thick, color = {rgb,1:red,0.993; green,0.906;blue, 0.144}];
\draw[thick, color = {rgb,1:red,0.794; green,0.881;blue, 0.120}];
\draw[thick, color = {rgb,1:red,0.267; green,0.005;blue, 0.329}];
\draw[thick, color = {rgb,1:red,0.283; green,0.136;blue, 0.453}];
\draw[thick, color = {rgb,1:red,0.896; green,0.894;blue, 0.096}];
\draw[thick, color = {rgb,1:red,0.259; green,0.252;blue, 0.525}];
\draw[thick, color = {rgb,1:red,0.196; green,0.395;blue, 0.555}];
\draw[thick, color = {rgb,1:red,0.232; green,0.318;blue, 0.545}];
\draw[thick, color = {rgb,1:red,0.243; green,0.292;blue, 0.539}];


(0.18207673092707524, 0.6591979206257018)

In [6]:

net.vertices*0.13468700594861674
net.q*100

# 10/74.24621202

array([1.106875 , 0.4025   , 0.4025   , 1.308125 , 1.2075   , 0.301875 ,
       0.503125 , 1.2075   , 0.3521875, 0.4528125, 0.4025   , 0.4025   ])

Here is the same network but elements 11 and 12 are combined into a single element.

In [7]:
# # Note that the coordinates of the vertices will change after equilibrium is reached.
# model_name  = 'Validation_structure_1'
# vertices    = np.array([[-10, 0, 0], [-5, 0,0], [0, 0, 0], [5, 0, 0], [10, 0, 0], [0,-10,0], [0,-5,0], [0,5,0], [0,10,0]])*10  # The coordinates of the vertices in mm
# edges       = [[0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [6, 2], [2, 7], [7, 8], [1, 6], [6, 3], [3, 7], [7,1]]                  # The edges of the network.
# paths       = [[0, 1, 2, 3], [4, 5, 6,7], [11, 8, 9, 10]]   # 3D printable paths. Ensure an edge is not flipped.
# directions  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]          # Flip the curvature of an edge by setting the direction to -1.

# q_ring      = .7
# q_connectors = .5
# q_center    = .1
# q           = np.array([q_connectors, q_center, 2*q_center, q_connectors, q_connectors, q_center, q_center, q_connectors, q_ring, q_ring, q_ring, q_ring])/20
# fixed       = [0, 4, 5, 8]

# # Create the network
# net = Network_custom.from_fd(vertices, edges, q, fixed, paths = paths, dir = directions)

# # The topology of structure is fixed after generation, but you can update force densities after making the network
# # q[0] = .10
# # net.update_shape(q)

# # Plot the network like this
# net.net_plot(color=True, elables = True, vlabels = False)

# (net.vertices == vertices).all() # Please understand that this is False

### Step 2: Materialize

In [8]:
# TPUc = {'E':130, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU conductive'} # Conductive TPU. Manufacturer Ninjatek Eel
TPU = {'E':77, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU non-conductive'} # Conductive TPU. Manufacturer Ninjatek Eel

file_path = os.path.join(BYU_UW_root,"Tensile Testing", 'Avg_Stress_Strain_Overture_TPU.csv')
stress_data, strain_data = net.load_stress_strain_curve(file_path)

TPU_nl = {'stress':strain_data, 'strain': stress_data, 'v':0.3897, 'p':1.18e-9, 'A': 0.078294515, 'name': 'TPU Overture'} # TPU Overture non-conductive

net.set_material(TPU) # By saving the material properties in the network, we can easily see how the network was constructed.

# If all elements will get the same material, you can use the following line
# E = [TPU['E']]*len(net.edges)
A = [TPU_nl['A']]*len(net.edges)
l0, l_scalar = net.materialize_nonlinear(A, stress_data, strain_data, interpolation_kind = 'cubic')
# l0, l_scalar = net.materialize(E, A)
# Yielding the initial lengths of each element. And the following scalar: min(l0/l1)
net.l0, net.l_scalar

(array([39.62509896, 49.0213568 , 49.45213693, 33.9061392 , 36.56705061,
        56.98223806, 41.92572942, 36.80808326, 71.65136829, 66.58963053,
        68.54680343, 66.0360618 ]),
 0.8698018851775938)

In [9]:
# # validate nl material method. This should be the same for the linear TPU
# strain_data = np.linspace(0, 0.5, 100)
# stress_data = TPU['E']*strain_data
# TPU_check = {'stress':strain_data, 'strain': stress_data, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU Check'}

# net.set_material(TPU_check) # By saving the material properties in the network, we can easily see how the network was constructed.
# l0, l_scalar = net.materialize_nonlinear(A, stress_data, strain_data, interpolation_kind = 'cubic')
# net.l0, net.l_scalar

### Step 3: Define elements as a curves
An (optional) optimization algorithm finds the vertex locations minimizing abs(l1-l0). Next the (optimized) network is scaled down, and edges are defined as arcs.

available error functions in the optimization algorithms are:
- 'no optimization' : Network is scaled down directly, and no alogirthm is applied
- 'standard'        : a standard L2-norm quantifies the error
- 'sigmoid'         : a sigmoid function skews the L2-norm to penalize too short edges more (b>0) or too long edges more (b<0)

Preliminary results shows best results using a standard L2 error function

In [10]:
# net.initialize_shape_optimizer(function_type = 'no optimization',  method = 'L-BFGS-B', params = None)
# net.initialize_shape_optimizer(function_type = 'standard',  method = 'L-BFGS-B',options ={"maxiter": 10000, "maxfun": 1500000, "maxls": 5000})
net.initialize_shape_optimizer(function_type = 'standard',  method = 'Gauss-Seidel',options ={"maxiter": 1000, "damping": .1, "correction_scalar": 1.5, "tol": 1e-6})
# net.initialize_shape_optimizer(function_type = 'standard',  method = 'trust-constr')
# net.initialize_shape_optimizer(function_type = 'sigmoid',  method = 'L-BFGS-B', params = {'a': 4, 'b': -1})
net.optimize_vertices()
reference_point = [0,0,0]                         # The network will be scaler relative to this point
net.scale_vertices(reference_point, net.l_scalar, account_for_leafs = True) # If you don't provide a scalar, it will use network.l_scalar automatically

# #  You can plot the scaled network like this
# # net.net_plot(color=True, plot_type='scaled')

# # Determine the Radius and Angle of the circle that define the arc of each element
R, th = net.arc_param()
# # for the arc length (net.l1 * net.l_scalar) is used unless specified otherwise, for the cord length (net.l0) is used unless specified otherwise
xyz = net.arc_points(n = 10) 

net.net_plot(color=True, plot_type='arcs', elables=True, vlabels = True)
# net.net_plot(color=True, plot_type='optimized', elables=False, vlabels = False)

# np.min(R/net.l0), net.l_scalar, np.min(net.l0 - net.l1), np.max(net.l0 - net.l1)
net.vertices_optimized*0.13468700594861674

Iteration 0: Current error = 1093.1077237921002
Iteration 100: Current error = 7.867994325245223
Iteration 200: Current error = 2.636042541592965
Iteration 300: Current error = 2.552012664655636
Iteration 400: Current error = 2.5479028742426397
Iteration 500: Current error = 2.5431951267204473
Iteration 600: Current error = 2.5457396769880485
Iteration 700: Current error = 2.557192097215979
Iteration 800: Current error = 2.527728373018311
Iteration 900: Current error = 2.5523780854066436
Final error: 2.551650854481524


array([[-8.13764814,  8.27019118,  0.        ],
       [-4.24222967,  4.62069035,  0.        ],
       [ 0.83939488,  0.49462741,  0.        ],
       [ 4.70923124, -4.85933313,  0.        ],
       [ 7.99540173, -8.03031129,  0.        ],
       [-8.06830025, -8.31902625,  0.        ],
       [-4.33114114, -5.10962775,  0.        ],
       [ 4.7527712 ,  4.47957248,  0.        ],
       [ 8.16474004,  8.07559977,  0.        ]])

In [11]:
%matplotlib qt
import matplotlib.animation as animation
ani = net.ShapeOptimizer.animate_optimization()
writer = animation.FFMpegWriter(fps=15)
ani.save(os.path.join(BYU_UW_root, 'images', 'form finding animations', f'form_finding_{model_name}_{0}.mp4'), writer=writer)

Flipping edge 2, 6, and 12 would make the network smoother

In [12]:
# net.flip_curve(2, n = 10)          # Flip the curvature of one edge
net.auto_flip_curves(n = 10)        # Automatically flip the curvature of the edges. Directions will become 1, -1, 1, -1, ...
net.flip_curves()                   # Flip all the edges.
net.flip_curves([8], n = 10)       # Flip the curvature of multiple edges
net.net_plot(color=True, plot_type='arcs', elables=True)

In [15]:
scalar_all = 0.13468700594861674
net.vertices_scaled*scalar_all, R*scalar_all

(array([[-8.08854089,  8.2168042 ,  0.        ],
        [-4.19378708,  4.56792606,  0.        ],
        [ 0.82980972,  0.48897919,  0.        ],
        [ 4.65545589, -4.80384375,  0.        ],
        [ 7.94169568, -7.97488877,  0.        ],
        [-8.01807825, -8.26002251,  0.        ],
        [-4.28168326, -5.05128022,  0.        ],
        [ 4.69849867,  4.42841963,  0.        ],
        [ 8.1107842 ,  8.02478071,  0.        ]]),
 189.1421868675933)

In [16]:
net.vertices

array([[-74.24621202,  74.24621202,   0.        ],
       [-34.06261627,  37.01244298,   0.        ],
       [  6.15631914,   3.25299698,   0.        ],
       [ 38.42749205, -38.80003746,   0.        ],
       [ 74.24621202, -74.24621202,   0.        ],
       [-74.24621202, -74.24621202,   0.        ],
       [-35.5991752 , -40.27183354,   0.        ],
       [ 37.56782572,  36.00276605,   0.        ],
       [ 74.24621202,  74.24621202,   0.        ]])

In [14]:
for edge_i, edge in enumerate(net.edges):
    v0, v1 = edge
    coor0, coor1 = net.vertices_scaled[v0], net.vertices_scaled[v1]
    R, th = net.R[edge_i], net.th[edge_i]
    center, theta0, theta1 = net._points_on_arc(coor0[:2], coor1[:2], R, print_parameters = True)
    # print(coor0[:2]/10, theta0*180/np.pi, theta1*180/np.pi, R)
    if R/10 > 10000:
        print(f"\draw ({coor0[0]*scalar_all:.3f}, {coor0[1]* scalar_all:.3f}) -- ({coor1[0]* scalar_all:.3f}, {coor1[1]* scalar_all:.3f});")
        continue
    if theta0 > theta1:
        print(f"\draw ({coor1[0]* scalar_all:.3f}, {coor1[1]* scalar_all:.3f}) arc ({theta0*180/np.pi:.3f}:{theta1*180/np.pi:.3f}:{-R* scalar_all:.3f});")
    else:
        print(f"\draw ({coor0[0]* scalar_all:.3f}, {coor0[1]* scalar_all:.3f}) arc ({theta0*180/np.pi:.3f}:{theta1*180/np.pi:.3f}:{R* scalar_all:.3f});")

\draw (-8.089, 8.217) -- (-4.194, 4.568);
\draw (-4.194, 4.568) arc (211.059:250.791:9.521);
\draw (0.830, 0.489) arc (196.202:235.517:9.707);
\draw (4.655, -4.804) -- (7.942, -7.975);
\draw (-8.018, -8.260) -- (-4.282, -5.051);
\draw (-4.282, -5.051) arc (298.521:336.089:11.705);
\draw (0.830, 0.489) arc (294.531:336.507:7.708);
\draw (4.698, 4.428) -- (8.111, 8.025);
\draw (-4.194, 4.568) arc (171.531:187.422:34.796);
\draw (-4.282, -5.051) arc (263.713:279.458:32.637);
\draw (4.655, -4.804) -- (4.698, 4.428);
\draw (4.698, 4.428) arc (87.754:90.448:189.142);


<>:8: SyntaxWarning:

invalid escape sequence '\d'

<>:11: SyntaxWarning:

invalid escape sequence '\d'

<>:13: SyntaxWarning:

invalid escape sequence '\d'

<>:8: SyntaxWarning:

invalid escape sequence '\d'

<>:11: SyntaxWarning:

invalid escape sequence '\d'

<>:13: SyntaxWarning:

invalid escape sequence '\d'

C:\Users\thijs\AppData\Local\Temp\ipykernel_22136\2300754454.py:8: SyntaxWarning:

invalid escape sequence '\d'

C:\Users\thijs\AppData\Local\Temp\ipykernel_22136\2300754454.py:11: SyntaxWarning:

invalid escape sequence '\d'

C:\Users\thijs\AppData\Local\Temp\ipykernel_22136\2300754454.py:13: SyntaxWarning:

invalid escape sequence '\d'



### Step 4: Account for intersections. 
Curved paths and intersections are automatically set up in the backend

In [ ]:
printing_params = load_params(r'DATA/NT_Eel_0.2mm_og.json')
# When no interpolation function is provided, linear interpolation is used. No other interpolation function is implemented (yet?).
# net.jump_at_intersection(intersection_width = 2, intersection_height = 2, interpolation_function=None) # These settings are just for visibility, this would be way to much
# These setting are more appropriate for printing
net.jump_at_intersection(intersection_width = printing_params['d_nozzle']*1.5, intersection_height = printing_params['layer_height'], interpolation_function=None) 
net.net_plot(color=True, plot_type='arcs', elables=True)

Add loops to easily attach the printed network to a frame

In [ ]:
alpha_loop = np.deg2rad(40) # The angle of the loop
L_loop  = 8                # The length of the loop
n_points = 10               # The number of points in the loop

start_loop_bools = [True, True, False]
end_loop_bools = [True, True, False]

net.all_loop_to_path(start_loop_bools, end_loop_bools, L_loop, alpha_loop, n_points)

Sometimes it takes a while before material starts extruding. This should preferably be fixed in the printer set up, but can me forced by adding a running start to a path

In [ ]:
start_loop_bools = [False, False, False]
end_loop_bools = [False, False, False]
L_loop  = 2
n_points = 5
net.add_running_start(start_loop_bools, end_loop_bools, L_loop, n_points)

In [ ]:
net.save_network(os.path.join(BYU_UW_root, 'networks', model_name + '_net.pkl'))

### Step 5: Generate G-code
Import and finalize printing parameters for materials and starting and end .gcode for the top. The start gcode has additional settings for temperatures and Linear Advance (K-factor). Linear advance is important for TPU as it is very visco-elastic. Linear advance can account for this

In [ ]:
printing_params = load_params(r'DATA/NT_Eel_0.2mm_og.json')
start_gcode     = open(r'DATA/start_gcode.gcode', 'r').read()
end_gcode       = open(r'DATA/end_gcode.gcode', 'r').read()

temperature_settings = {'first_layer_bed_temperature': 65, 'first_layer_temperature':205, 'K-factor': 0.20}
g_code = replace_brackets(start_gcode, temperature_settings)

comment = ''

bed_width = 230
bed_height = 210

gen = G_code_generator(printing_params=printing_params)

printing_params['print_feedrate']

Make a Purge Line

In [ ]:
point0, point1 = [20,15,0.3], [90,15,0.3]
point2, point3 = [90,10,0.3], [20,10,0.3]
g_code += gen.move_to_point(point0[0:2], point0[2] + printing_params['nozzle_lift'], comment='Move to start point')
g_code += gen.move_to_point(point0[0:2], point0[2], comment='Lower Nozzle')
g_code += gen.unretract()
g_code += gen._print_line(
        point0=point0,
        point1=point1,
        move_to_start=False, # move to start point without extruding
        extrude_factor=printing_params['extrude_factor']*2.5,
        comment=comment)
g_code += gen.retract()
g_code += gen.move_to_point(point2[0:2], point2[2] + printing_params['nozzle_lift'], comment='Move to start point')
g_code += gen.move_to_point(point2[0:2], point2[2], comment='Lower Nozzle')
g_code += gen.unretract()
g_code += gen._print_line(
        point0=point2,
        point1=point3,
        move_to_start=False, # move to start point without extruding
        extrude_factor=printing_params['extrude_factor']*2.5,
        comment=comment)
g_code += gen.retract()
g_code += gen.wipe(np.pi) # Wipe the nozzle horizontally

Make the paths

In [ ]:
for path_i, cor_list in enumerate(net.paths_xyz):
    g_code += '\n;Path (' + str(path_i) + ' ' + str(path_i) + ')\n'
    cor_list   = np.array(cor_list)
    # Move the coordinates to the center of the bed and add the layer height
    cor_list[:,0] += bed_width/2
    cor_list[:,1] += bed_height/2 - 1
    cor_list[:,2] += printing_params['layer_height']
    g_code += '\n'
    # Move the coordinates to the start point
    g_code += gen.move_to_point(cor_list[0][0:2], cor_list[0][2] + printing_params['nozzle_lift'], comment='Move to start point')
    # Lower the nozzle
    g_code += gen.move_to_point(cor_list[0][0:2], cor_list[0][2], comment='Lower Nozzle')
    # Unretract the filament
    g_code += gen.unretract()
    # Print the path
    for point0, point1 in zip(cor_list[:-1], cor_list[1:]):
        g_code += gen._print_line(
            point0=point0,
            point1=point1,
            move_to_start=False, # move to start point without extruding
            extrude_factor = printing_params['extrude_factor'],
            comment=comment)
    # Retract the filament
    g_code += gen.retract()
    # Wipe the nozzle
    g_code += gen.wipe_from_last_points(g_code)    
    # Raise the nozzle
    g_code += gen.move_to_point(point1[0:2], point1[2] + printing_params['nozzle_lift'], speed_factor=0.5, comment='Raise Nozzle')

g_code += end_gcode
with open(os.path.join('DATA', 'generated_gcodes', model_name + '.gcode'), "w") as g_code_file:
    g_code_file.write(g_code)
print('G-code generated')

In [ ]:
net.paths_xyz[-1]

In [ ]:
minx, miny = 90, 90
maxx, maxy = 0, 0
for path_i, cor_list in enumerate(net.paths_xyz):
    cor_list   = np.array(cor_list)
    minx = min(minx, np.min(cor_list[:,0]))
    miny = min(miny, np.min(cor_list[:,1]))
    maxx = max(maxx, np.max(cor_list[:,0]))
    maxy = max(maxy, np.max(cor_list[:,1]))

minx + bed_width/2, miny + bed_height/2, maxx + bed_width/2, maxy + bed_height/2