In [1]:
# Ensure you have the following installed:
# numpy
# os
# compas
# compas_fd
# warnings
# traceback
# pickle

# Install by running:
# !pip install -r requirements.txt

In [2]:
import numpy as np
import pickle
import pandas as pd

# G-code generation codes are cloned from https://github.com/tibor-barsi/GcodeGenerator. Tibor Barsi is the author of the code, and was a PhD student at the Ladisk lab of the University of Ljubljana
#  We should be careful with crediting the author of the code, if we ever want to make these code public.
from src.g_code_generation_copy.gcode_generator import G_code_generator
from src.g_code_generation_copy.tool_changer_functions import save_params, load_params, printer_start, load_tool, unload_tool, tool_change, take_photo, play_sound, printer_stop
# from src.additional_functions import *
from src.network import Network_custom, replace_brackets
import os

BYU_UW_root = r"G:\.shortcut-targets-by-id\1k1B8zPb3T8H7y6x0irFZnzzmfQPHMRPx\Illimited Lab Projects\Research Projects\Spiders\BYU-UW"

### Step 1: Define the network

In [3]:
# Note that the coordinates of the vertices will change after equilibrium is reached.
vertices    = np.array([[-10, 0, 0], [-5, 0,0], [0, 0, 0], [5, 0, 0], [10, 0, 0], [0,-10,0], [0,-5,0], [0,5,0], [0,10,0]])*10  # The coordinates of the vertices in mm
edges       = [[0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [6, 2], [2, 7], [7, 8], [1, 6], [6, 3], [3, 7], [7,1]]                  # The edges of the network.
paths       = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]   # 3D printable paths. Ensure an edge is not flipped.
directions  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]          # Flip the curvature of an edge by setting the direction to -1.

scalar = 80
q_ring      = .5
q_connectors = .8
q_center    = .2
q           = np.array([q_connectors, q_center, q_center, q_connectors, q_connectors, q_center, q_center, q_connectors, q_ring, q_ring, q_ring, q_ring])/scalar
q[2]        = 1.5/scalar
q[-1]        = 1.5/scalar
fixed       = [0, 4, 5, 8]
# model_name  = 'VS_ring{}_connectors{}_center{}_as{}'.format(q_ring, q_connectors, q_center, q[2]*scalar)
model_name  = 'VS_ring{}_connectors{}_center{}_as{}_asr{}_s{}'.format(q_ring, q_connectors, q_center, q[2]*scalar, q[-1]*scalar, scalar)

# Create the network
net = Network_custom.from_fd(vertices, edges, q, fixed, paths = paths, dir = directions)

# The topology of structure is fixed after generation, but you can update force densities after making the network
# q[0] = .10
# net.update_shape(q)

# Plot the network like this
net.net_plot(color=True, elables = True, vlabels = False)

(net.vertices == vertices).all() # Please understand that this is False
np.max(net.f)/0.078294515

# import matplotlib.pyplot as plt
# cmap = plt.get_cmap('viridis')

# Convert to TikZ RGB format
# f_plot = (net.f - np.min(net.f)) / (np.max(net.f) - np.min(net.f))
# for val in f_plot:
#     r, g, b, _ = cmap(val)  # Get RGBA (ignore A)color={rgb,1:red,0.282;green,0.141;blue,0.458}
#     print("\draw[thick, color = {" + f"rgb,1:red,{r:.3f}; green,{g:.3f};blue, {b:.3f}"+"}]")

# np.min(net.f), np.max(net.f), q

9.202906892601156

Here is the same network but elements 11 and 12 are combined into a single element.

In [4]:
# # Note that the coordinates of the vertices will change after equilibrium is reached.
# model_name  = 'Validation_structure_1'
# vertices    = np.array([[-10, 0, 0], [-5, 0,0], [0, 0, 0], [5, 0, 0], [10, 0, 0], [0,-10,0], [0,-5,0], [0,5,0], [0,10,0]])*10  # The coordinates of the vertices in mm
# edges       = [[0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [6, 2], [2, 7], [7, 8], [1, 6], [6, 3], [3, 7], [7,1]]                  # The edges of the network.
# paths       = [[0, 1, 2, 3], [4, 5, 6,7], [11, 8, 9, 10]]   # 3D printable paths. Ensure an edge is not flipped.
# directions  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]          # Flip the curvature of an edge by setting the direction to -1.

# q_ring      = .7
# q_connectors = .5
# q_center    = .1
# q           = np.array([q_connectors, q_center, 2*q_center, q_connectors, q_connectors, q_center, q_center, q_connectors, q_ring, q_ring, q_ring, q_ring])/20
# fixed       = [0, 4, 5, 8]

# # Create the network
# net = Network_custom.from_fd(vertices, edges, q, fixed, paths = paths, dir = directions)

# # The topology of structure is fixed after generation, but you can update force densities after making the network
# # q[0] = .10
# # net.update_shape(q)

# # Plot the network like this
# net.net_plot(color=True, elables = True, vlabels = False)

# (net.vertices == vertices).all() # Please understand that this is False

### Step 2: Materialize

In [5]:
# TPUc = {'E':130, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU conductive'} # Conductive TPU. Manufacturer Ninjatek Eel
TPU = {'E':77, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU non-conductive'} # Conductive TPU. Manufacturer Ninjatek Eel

file_path = os.path.join(BYU_UW_root, 'Avg_Stress_Strain_Overture_TPU.csv')
stress_data, strain_data = net.load_stress_strain_curve(file_path)

TPU_nl = {'stress':strain_data, 'strain': stress_data, 'v':0.3897, 'p':1.18e-9, 'A': 0.078294515, 'name': 'TPU Overture'} # TPU Overture non-conductive

net.set_material(TPU) # By saving the material properties in the network, we can easily see how the network was constructed.

# If all elements will get the same material, you can use the following line
# E = [TPU['E']]*len(net.edges)
A = [TPU_nl['A']]*len(net.edges)
l0, l_scalar = net.materialize_nonlinear(A, stress_data, strain_data, interpolation_kind = 'cubic')
# l0, l_scalar = net.materialize(E, A)
# Yielding the initial lengths of each element. And the following scalar: min(l0/l1)
net.l0, net.l_scalar

(array([50.07737186, 49.08010757, 12.09604811, 50.69898368, 49.84771761,
        40.56410569, 41.68027759, 50.53656819, 53.21507323, 44.97496129,
        48.85575341, 25.56737076]),
 0.6950005717916775)

In [6]:
# # validate nl material method. This should be the same for the linear TPU
# strain_data = np.linspace(0, 0.5, 100)
# stress_data = TPU['E']*strain_data
# TPU_check = {'stress':strain_data, 'strain': stress_data, 'v':0.3897, 'p':1.18e-9, 'A':0.11*0.71, 'name': 'TPU Check'}

# net.set_material(TPU_check) # By saving the material properties in the network, we can easily see how the network was constructed.
# l0, l_scalar = net.materialize_nonlinear(A, stress_data, strain_data, interpolation_kind = 'cubic')
# net.l0, net.l_scalar

### Step 3: Define elements as a curves
An (optional) optimization algorithm finds the vertex locations minimizing abs(l1-l0). Next the (optimized) network is scaled down, and edges are defined as arcs.

available error functions in the optimization algorithms are:
- 'no optimization' : Network is scaled down directly, and no alogirthm is applied
- 'standard'        : a standard L2-norm quantifies the error
- 'sigmoid'         : a sigmoid function skews the L2-norm to penalize too short edges more (b>0) or too long edges more (b<0)

Preliminary results shows best results using a standard L2 error function

In [7]:
# net.initialize_shape_optimizer(function_type = 'no optimization',  method = 'L-BFGS-B', params = None)
# net.initialize_shape_optimizer(function_type = 'standard',  method = 'L-BFGS-B',options ={"maxiter": 10000, "maxfun": 1500000, "maxls": 5000})
net.initialize_shape_optimizer(function_type = 'standard',  method = 'Gauss-Seidel',options ={"maxiter": 1000, "damping": .1, "correction_scalar": 1.5, "tol": 1e-6})
# net.initialize_shape_optimizer(function_type = 'standard',  method = 'trust-constr')
# net.initialize_shape_optimizer(function_type = 'sigmoid',  method = 'L-BFGS-B', params = {'a': 4, 'b': -1})
net.optimize_vertices()
reference_point = [0,0,0]                         # The network will be scaler relative to this point
net.scale_vertices(reference_point, net.l_scalar, account_for_leafs = True) # If you don't provide a scalar, it will use network.l_scalar automatically

# #  You can plot the scaled network like this
# # net.net_plot(color=True, plot_type='scaled')

# # Determine the Radius and Angle of the circle that define the arc of each element
R, th = net.arc_param()
# # for the arc length (net.l1 * net.l_scalar) is used unless specified otherwise, for the cord length (net.l0) is used unless specified otherwise
xyz = net.arc_points(n = 10) 

net.net_plot(color=True, plot_type='arcs', elables=True, vlabels = True)
# net.net_plot(color=True, plot_type='optimized', elables=False, vlabels = False)

# np.min(R/net.l0), net.l_scalar, np.min(net.l0 - net.l1), np.max(net.l0 - net.l1)
net.vertices_optimized/10

Iteration 0: Current error = 1082.1429046877467
Iteration 100: Current error = 4.77804537793088
Iteration 200: Current error = 3.837883878351295
Iteration 300: Current error = 3.8198846056619438
Iteration 400: Current error = 3.818523725383758
Converged after 475 iterations.
Final error: 3.8183616106697076


array([[-7.69251198,  0.30335489,  0.        ],
       [-2.73441969,  1.00657697,  0.        ],
       [ 2.05534803,  0.00971313,  0.        ],
       [ 3.15127946, -0.07196656,  0.        ],
       [ 8.22855612, -0.02775169,  0.        ],
       [ 0.06092464, -8.48192821,  0.        ],
       [ 0.13122693, -3.49763075,  0.        ],
       [-0.91508217,  2.82456017,  0.        ],
       [-0.25331537,  7.83830986,  0.        ]])

In [8]:
%matplotlib qt
import matplotlib.animation as animation
ani = net.ShapeOptimizer.animate_optimization()
writer = animation.FFMpegWriter(fps=15)
ani.save(os.path.join(BYU_UW_root, 'images', 'form finding animations', f'form_finding_{model_name}_{0}.mp4'), writer=writer)

Flipping edge 2, 6, and 12 would make the network smoother

In [9]:
# net.flip_curve(2, n = 10)          # Flip the curvature of one edge
net.auto_flip_curves(n = 10)        # Automatically flip the curvature of the edges. Directions will become 1, -1, 1, -1, ...
net.flip_curves()                   # Flip all the edges.
net.flip_curves([2,5], n = 10)       # Flip the curvature of multiple edges
net.net_plot(color=True, plot_type='arcs', elables=True)

In [10]:
net.vertices_scaled/10, R/10

(array([[-7.63396583,  0.2817916 ,  0.        ],
        [-2.67585068,  0.98501692,  0.        ],
        [ 2.01132418,  0.00950508,  0.        ],
        [ 3.08378166, -0.07042509,  0.        ],
        [ 8.1534878 , -0.02627616,  0.        ],
        [ 0.05811417, -8.40699038,  0.        ],
        [ 0.12841615, -3.42271439,  0.        ],
        [-0.89548187,  2.76406043,  0.        ],
        [-0.23418324,  7.77426316,  0.        ]]),
 array([1.59401225e+06, 6.37282422e+00, 7.28688382e-01, 1.61379877e+06,
        1.58670213e+06, 4.40781766e+00, 4.27157463e+00, 1.60862893e+06,
        8.00977450e+00, 1.15239672e+01, 1.55512693e+06, 4.17038752e+00]))

### Step 4: Account for intersections. 
Curved paths and intersections are automatically set up in the backend

In [11]:
printing_params = load_params(r'DATA/NT_Eel_0.2mm_og.json')
# When no interpolation function is provided, linear interpolation is used. No other interpolation function is implemented (yet?).
# net.jump_at_intersection(intersection_width = 2, intersection_height = 2, interpolation_function=None) # These settings are just for visibility, this would be way to much
# These setting are more appropriate for printing
net.jump_at_intersection(intersection_width = printing_params['d_nozzle']*1.5, intersection_height = printing_params['layer_height'], interpolation_function=None) 
net.net_plot(color=True, plot_type='arcs', elables=True)

Add loops to easily attach the printed network to a frame

In [12]:
alpha_loop = np.deg2rad(40) # The angle of the loop
L_loop  = 8                # The length of the loop
n_points = 60               # The number of points in the loop

start_loop_bools = [True, True, False]
end_loop_bools = [True, True, False]

net.all_loop_to_path(start_loop_bools, end_loop_bools, L_loop, alpha_loop, n_points)

Sometimes it takes a while before material starts extruding. This should preferably be fixed in the printer set up, but can me forced by adding a running start to a path

In [13]:
start_loop_bools = [False, False, False]
end_loop_bools = [False, False, False]
L_loop  = 2
n_points = 5
net.add_running_start(start_loop_bools, end_loop_bools, L_loop, n_points)

In [14]:
net.save_network(os.path.join(BYU_UW_root, 'networks', model_name + '_net.pkl'))

### Step 5: Generate G-code
Import and finalize printing parameters for materials and starting and end .gcode for the top. The start gcode has additional settings for temperatures and Linear Advance (K-factor). Linear advance is important for TPU as it is very visco-elastic. Linear advance can account for this

In [15]:
printing_params = load_params(r'DATA/NT_Eel_0.2mm_og.json')
start_gcode     = open(r'DATA/start_gcode.gcode', 'r').read()
end_gcode       = open(r'DATA/end_gcode.gcode', 'r').read()

temperature_settings = {'first_layer_bed_temperature': 65, 'first_layer_temperature':205, 'K-factor': 0.20}
g_code = replace_brackets(start_gcode, temperature_settings)

comment = ''

bed_width = 230
bed_height = 210

gen = G_code_generator(printing_params=printing_params)

printing_params['print_feedrate']

15.0

Make a Purge Line

In [16]:
point0, point1 = [20,15,0.3], [90,15,0.3]
point2, point3 = [90,10,0.3], [20,10,0.3]
g_code += gen.move_to_point(point0[0:2], point0[2] + printing_params['nozzle_lift'], comment='Move to start point')
g_code += gen.move_to_point(point0[0:2], point0[2], comment='Lower Nozzle')
g_code += gen.unretract()
g_code += gen._print_line(
        point0=point0,
        point1=point1,
        move_to_start=False, # move to start point without extruding
        extrude_factor=printing_params['extrude_factor']*2.5,
        comment=comment)
g_code += gen.retract()
g_code += gen.move_to_point(point2[0:2], point2[2] + printing_params['nozzle_lift'], comment='Move to start point')
g_code += gen.move_to_point(point2[0:2], point2[2], comment='Lower Nozzle')
g_code += gen.unretract()
g_code += gen._print_line(
        point0=point2,
        point1=point3,
        move_to_start=False, # move to start point without extruding
        extrude_factor=printing_params['extrude_factor']*2.5,
        comment=comment)
g_code += gen.retract()
g_code += gen.wipe(np.pi) # Wipe the nozzle horizontally

Make the paths

In [17]:
for path_i, cor_list in enumerate(net.paths_xyz):
    g_code += '\n;Path (' + str(path_i) + ' ' + str(path_i) + ')\n'
    cor_list   = np.array(cor_list)
    # Move the coordinates to the center of the bed and add the layer height
    cor_list[:,0] += bed_width/2
    cor_list[:,1] += bed_height/2 - 1
    cor_list[:,2] += printing_params['layer_height']
    g_code += '\n'
    # Move the coordinates to the start point
    g_code += gen.move_to_point(cor_list[0][0:2], cor_list[0][2] + printing_params['nozzle_lift'], comment='Move to start point')
    # Lower the nozzle
    g_code += gen.move_to_point(cor_list[0][0:2], cor_list[0][2], comment='Lower Nozzle')
    # Unretract the filament
    g_code += gen.unretract()
    # Print the path
    for point0, point1 in zip(cor_list[:-1], cor_list[1:]):
        g_code += gen._print_line(
            point0=point0,
            point1=point1,
            move_to_start=False, # move to start point without extruding
            extrude_factor = printing_params['extrude_factor'],
            comment=comment)
    # Retract the filament
    g_code += gen.retract()
    # Wipe the nozzle
    g_code += gen.wipe_from_last_points(g_code)    
    # Raise the nozzle
    g_code += gen.move_to_point(point1[0:2], point1[2] + printing_params['nozzle_lift'], speed_factor=0.5, comment='Raise Nozzle')

g_code += end_gcode
with open(os.path.join('DATA', 'generated_gcodes', model_name + '.gcode'), "w") as g_code_file:
    g_code_file.write(g_code)
print('G-code generated')

G-code generated


In [18]:
net.paths_xyz[-1]

array([[-26.75850681,   9.8501692 ,   0.2       ],
       [-17.0811693 ,   0.74342038,   0.        ],
       [ -9.04264368,  -9.83797088,   0.        ],
       [ -2.86418159, -21.60276334,   0.        ],
       [  1.28416154, -34.22714391,   0.2       ],
       [  9.86673678, -26.97036498,   0.        ],
       [ 17.70158433, -18.91203997,   0.        ],
       [ 24.71417892, -10.12881987,   0.        ],
       [ 30.83781657,  -0.70425091,   0.2       ],
       [ 20.8896494 ,   6.38195118,   0.        ],
       [ 10.9414878 ,  13.46816108,   0.        ],
       [  0.99333176,  20.55437879,   0.        ],
       [ -8.95481872,  27.64060431,   0.2       ],
       [-14.38151305,  24.27508411,   0.        ],
       [-19.23078592,  20.12053356,   0.        ],
       [-23.38894644,  15.27435582,   0.        ],
       [-26.75850681,   9.8501692 ,   0.2       ]])

In [19]:
minx, miny = 90, 90
maxx, maxy = 0, 0
for path_i, cor_list in enumerate(net.paths_xyz):
    cor_list   = np.array(cor_list)
    minx = min(minx, np.min(cor_list[:,0]))
    miny = min(miny, np.min(cor_list[:,1]))
    maxx = max(maxx, np.max(cor_list[:,0]))
    maxy = max(maxy, np.max(cor_list[:,1]))

minx + bed_width/2, miny + bed_height/2, maxx + bed_width/2, maxy + bed_height/2

(28.01630515830557, 10.210788310719565, 207.2535703212352, 193.39845325815784)