## Network validation
This scripts is meant to validate that the designed vertex location match the real locations.

The theoratical vertices are found in a network model as net.vertices.
The real vertices are retrieved from a picture of the network suspended in a frame. The following steps are required to enable the comparison:
- Conventional cameras have some distortion. (straight lines appear to be curved). The camera distortion can be found from a set of images of a checkerboard with known dimensions. The image is then undistorted.
- Ideally, a picture of the network is taken exaclty orthogonal to the subject. The homography of the camera angle with respect to the frame is determined. The frame contains markers on a straight plane with known world coordinates. With the homography known an image can be warped such that it appears to take the frame exactly orthogonal to the frame.

Finally, the vertices are selected in the image and they can be compared to their theoratical locations.

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import glob
from src.network import Network_custom
import plotly.io as pio
pio.renderers.default = 'browser'

### Open the network model

In [19]:
BYU_UW_root = r"G:\.shortcut-targets-by-id\1k1B8zPb3T8H7y6x0irFZnzzmfQPHMRPx\Illimited Lab Projects\Research Projects\Spiders\BYU-UW"
# model_name  = 'Validation_structure_1'
# model_name = 'VS_ring0.5_connectors0.8_center0.2_as1.5_asr1.5_s110'
# model_name = 'unit_cell_loop_size_q_(1.5, 2, 0.7)'
model_name = 'unit_cell_loop_size_q_(1.5, 2, 0.7)_10'
# model_name = 'unit_cell_even_q_0.35'
try:
    net = Network_custom.load_network(os.path.join(BYU_UW_root, 'networks', model_name + '.pkl'))
    rotate45 = False
except:
    net = Network_custom.load_network(os.path.join(BYU_UW_root, 'networks', model_name + '_net.pkl'))
    rotate45 = True
net.net_plot(color=True, elables = False, vlabels = True)

picture_number = 2
model_name_im = model_name + f"_{picture_number}"


### Load a set of images of checker boards
Internal camera and distortion parameters are determined of the camera. The process needs to be repeated when changing anything on the camera set up (lens/zoom/aperture/etc..). Make sure that auto-focus is off

In [20]:
# checkerboard_size = (8, 12)  # Number of inner corners per a chessboard row and column
# square_size = 10 #6.85/(checkerboard_size[0]+1) * 0.0254

# # Termination criteria for corner sub-pixel accuracy
# criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# # Prepare object points based on the real-world dimensions of the checkerboard
# objp = np.zeros((checkerboard_size[0] * checkerboard_size[1], 3), np.float32)
# objp[:, :2] = np.mgrid[0:checkerboard_size[1], 0:checkerboard_size[0]].T.reshape(-1, 2)
# objp *= square_size

# # Arrays to store object points and image points from all the images
# objpoints = []  # 3d points in real-world space
# imgpoints = []  # 2d points in image plane

# # Load images
# # images = glob.glob(os.path.join(BYU_UW_root,'Calibration images/*.jpg' ))
# images = glob.glob(os.path.join(BYU_UW_root,'Calibration images/new3/*.jpg' ))

# for fname in images:
#     img = cv2.imread(fname)
#     img_shape = img.shape[:2]
#     img_aspect_ratio = img_shape[1] / img_shape[0]
#     gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#     # Find the chessboard corners
#     ret, corners = cv2.findChessboardCorners( 
#                     gray, (12, 8),  
#                     cv2.CALIB_CB_ADAPTIVE_THRESH + 
#                     cv2.CALIB_CB_NORMALIZE_IMAGE) 
#     # If found, add object points, image points (after refining them)
#     if ret:
#         objpoints.append(objp.copy())
#         corners2 = cv2.cornerSubPix(gray, corners, (31, 31), (-1, -1), criteria)
#         imgpoints.append(corners2)

#         # Draw and display the corners
#         cv2.drawChessboardCorners(img, checkerboard_size, corners2, ret)
#         # resized_image = cv2.resize(img, (400, int(400 / img_aspect_ratio)))
#         cv2.imshow('img', img)
#         # cv2.waitKey(1)
        
# cv2.destroyAllWindows()

# # Calibrate the camera
# flags = cv2.CALIB_FIX_K3 + cv2.CALIB_FIX_K4 + cv2.CALIB_FIX_K5 + cv2.CALIB_FIX_K6
# ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
#     objpoints, imgpoints, gray.shape[::-1], None, None, flags=flags
# )
# # Print the camera matrix and distortion coefficients
# print("Camera matrix:\n", mtx)
# print("Distortion coefficients:\n", dist)

# # Check calibration results. A good mean projection error is <1.0
# mean_error = 0
# for i in range(len(objpoints)):
#     imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
#     error = cv2.norm(imgpoints[i], imgpoints2, cv2.NORM_L2) / len(imgpoints2)
#     mean_error += error
# print("Mean reprojection error:", mean_error / len(objpoints))

# img = cv2.imread(images[-1])
# fig, ax = plt.subplots(1, 2, figsize=(10, 5))
# ax[0].imshow(img)
# ax[0].set_title('Original Image')
# ax[1].imshow(cv2.undistort(img, mtx, dist))
# ax[1].set_title('Undistorted Image')
# plt.show()


In [21]:
# import matplotlib.pyplot as plt

# import numpy as np
# import os
# mtx = np.array([[2.25105751e+04, 0.00000000e+00, 2.49549539e+03],
#         [0.00000000e+00, 2.25183605e+04, 2.84911943e+03],
#         [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

# dist = np.array([[ 0.56985739,  1.09785385, -0.00920809,  0.02059732,  3.93628828]])

mtx = np.array([[2.68908731e+04, 0.00000000e+00, 2.26405663e+03],
 [0.00000000e+00, 2.68576281e+04, 2.94945084e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

dist = np.array([[ 0.8429211,  -0.30036892, -0.00690671,  0.01086315,  0.        ]])


%matplotlib qt

# # === Load image ===
image_name = model_name_im + ".jpg"
image_path = os.path.join(BYU_UW_root, 'measuerement images', image_name)
original_image = plt.imread(image_path)
height, width, _ = original_image.shape

img_und = cv2.undistort(original_image, mtx, dist[:4])

mean_img = (original_image + img_und) / 2
mean_img = mean_img.astype(np.uint8)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(mean_img)


checker_image_name = "checkerboard0.JPG"
checker_image_path = os.path.join(BYU_UW_root, 'measuerement images', checker_image_name)
checker_image = plt.imread(checker_image_path)

checker_image_und = cv2.undistort(checker_image, mtx, dist[:4])

checker_image_mean = (checker_image + checker_image_und) / 2
checker_image_mean = checker_image_mean.astype(np.uint16)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(checker_image)


original_image = img_und
# checker_image = checker_image_und

### Load an image of the frame and click on the markers

In [22]:
from matplotlib.widgets import Button
# === State trackers ===
rotation_state = [0]       # in degrees, e.g. 0, 90, 180, 270
flip_ud_state = [False]    # vertical flip state
image_displayed = [None]   # store current image
ax = [None]                # access axis in handlers

def apply_transform():
    """Apply rotation and flip to the original image and return the transformed image."""
    img = original_image.copy()
    # Flip up-down if needed
    if flip_ud_state[0]:
        img = np.flipud(img)
    # Rotate based on rotation_state
    k = rotation_state[0] // 90
    img = np.rot90(img, k=k)
    return img

def update_display():
    ax[0].clear()
    transformed = apply_transform()
    ax[0].imshow(transformed)
    ax[0].axis("off")
    ax[0].set_title(f"Rot: {rotation_state[0]}°, FlipUD: {flip_ud_state[0]}")
    ax[0].figure.canvas.draw()

def rotate_plus(event):
    rotation_state[0] = (rotation_state[0] + 90) % 360
    update_display()

def rotate_minus(event):
    rotation_state[0] = (rotation_state[0] - 90) % 360
    update_display()

def flip_ud(event):
    flip_ud_state[0] = not flip_ud_state[0]
    update_display()

def on_close(event):
    global original_image
    original_image = apply_transform()
    height, width, _ = original_image.shape
    print("Image window closed. `original_image` updated with final transformation.")

# === Plot image ===
fig, main_ax = plt.subplots(figsize=(12, 12))
ax[0] = main_ax
fig.canvas.manager.set_window_title("Image Viewer")
image_displayed[0] = main_ax.imshow(apply_transform())
main_ax.axis("off")
main_ax.set_title(f"Rot: {rotation_state[0]}°, FlipUD: {flip_ud_state[0]}")
# Connect close event
fig.canvas.mpl_connect("close_event", on_close)

# === Buttons ===
button_fig, _ = plt.subplots(figsize=(3, 2))
button_fig.canvas.manager.set_window_title("Controls")

ax_rotp = plt.axes([0.1, 0.6, 0.8, 0.25])
ax_rotm = plt.axes([0.1, 0.35, 0.8, 0.25])
ax_flip = plt.axes([0.1, 0.1, 0.8, 0.25])

btn_rotp = Button(ax_rotp, "+90°")
btn_rotm = Button(ax_rotm, "-90°")
btn_flip = Button(ax_flip, "Flip Up/Down")

btn_rotp.on_clicked(rotate_plus)
btn_rotm.on_clicked(rotate_minus)
btn_flip.on_clicked(flip_ud)

plt.show()


In [23]:

# Initial axis limits
xlim_init, ylim_init = (0, width), (height, 0)
points = []  # Store clicked points
def on_click(event):
    """Reset view when clicking anywhere in the figure."""
    if event.button == 1:  # Left mouse button
        points.append((event.xdata, event.ydata))
        ax.plot(event.xdata, event.ydata, 'r.', label='real vertices')
        ax.set_xlim(xlim_init)
        ax.set_ylim(ylim_init)
        ax.figure.canvas.draw()

def on_scroll(event):
    """Zoom in/out at mouse position using the scroll wheel."""
    scale_factor = 1.3  # Zoom speed
    xlim, ylim = ax.get_xlim(), ax.get_ylim()

    if event.step > 0:  # Zoom in
        xlim_new = (event.xdata - (event.xdata - xlim[0]) / scale_factor,
                    event.xdata + (xlim[1] - event.xdata) / scale_factor)
        ylim_new = (event.ydata - (event.ydata - ylim[0]) / scale_factor,
                    event.ydata + (ylim[1] - event.ydata) / scale_factor)
    else:  # Zoom out
        xlim_new = (event.xdata - (event.xdata - xlim[0]) * scale_factor,
                    event.xdata + (xlim[1] - event.xdata) * scale_factor)
        ylim_new = (event.ydata - (event.ydata - ylim[0]) * scale_factor,
                    event.ydata + (ylim[1] - event.ydata) * scale_factor)

    ax.set_xlim(xlim_new)
    ax.set_ylim(ylim_new)
    fig.canvas.draw()

def on_motion(event):
    """Update ring cursor position."""
    if event.xdata is not None and event.ydata is not None:
        circle_outer.set_center((event.xdata, event.ydata))
        circle_inner.set_center((event.xdata, event.ydata))
        fig.canvas.draw_idle()

def on_motion2(event):
    """Update ring cursor position."""
    if event.xdata is not None and event.ydata is not None:
        circle.set_center((event.xdata, event.ydata))
        circle.set_center((event.xdata, event.ydata))
        fig.canvas.draw_idle()

def on_close(event):
    """Callback function to stop the event loop when the figure is closed."""
    plt.close()

# Display image
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(original_image)
ax.set_xlim(xlim_init)
ax.set_ylim(ylim_init)
ax.axis("off")

# Add quadrant markers
ax.text(width/2, height*.9, '1', color='r')
ax.text(width*.9, height/2, '2', color='r')
ax.text(width/2, height*.1, '3', color='r')
ax.text(width*.1, height/2, '4', color='r')
ax.set_title("Click on markers (in order). Zoom with scroll wheel.")

# Create ring cursor
circle_outer = plt.Circle((0, 0), radius=40, color='r', fill=False, lw=2)
circle_inner = plt.Circle((0, 0), radius=20, color='r', fill=False, lw=2)
ax.add_patch(circle_outer)
ax.add_patch(circle_inner)


# Connect events
fig.canvas.mpl_connect("button_press_event", on_click)
fig.canvas.mpl_connect("scroll_event", on_scroll)
fig.canvas.mpl_connect("motion_notify_event", on_motion)

plt.show()


Image window closed. `original_image` updated with final transformation.


In [24]:
# points = np.array([(3108.1745194618484, 3402.5666577771403),
#  (4642.920922553315, 1912.6263830304224),
#  (3143.682438629892, 391.1770490488246),
#  (1615.726921448857, 1880.5276926742765)])
points

[(3106.461517421706, 3403.8021503327177),
 (4616.727234909741, 1924.5659905629545),
 (3132.4174313825924, 420.92588907903246),
 (1616.1038240720675, 1882.460629651013)]

Use this points if you don't want to reassign the points everytime you run the script

In [ ]:
# Display image
points = []  # Store clicked points
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(aligned_checker_image)
ax.set_xlim(xlim_init)
ax.set_ylim(ylim_init)
ax.axis("off")

# Add quadrant markers
ax.text(width/2, height*.9, '1', color='r')
ax.text(width*.9, height/2, '2', color='r')
ax.text(width/2, height*.1, '3', color='r')
ax.text(width*.1, height/2, '4', color='r')
ax.set_title("Click on markers (in order). Zoom with scroll wheel.")

# Create ring cursor
circle_outer = plt.Circle((0, 0), radius=40, color='r', fill=False, lw=2)
circle_inner = plt.Circle((0, 0), radius=20, color='r', fill=False, lw=2)
ax.add_patch(circle_outer)
ax.add_patch(circle_inner)


# Connect events
fig.canvas.mpl_connect("button_press_event", on_click)
fig.canvas.mpl_connect("scroll_event", on_scroll)
fig.canvas.mpl_connect("motion_notify_event", on_motion)

plt.show()


In [ ]:
points_checker = np.array(points)
points_checker

### Calibrate the camera angle with the known coordinates of the markers.
This will break if the order of the coordinates are misaligned. Also notice that the y-axis is inverted when working with images, ensure your know cordinate list is set up accordingly

In [8]:
points_nonaligned    = np.array(points)
distance_between_markers_mm = 155.563491 #148.49 # mm 155.669 # 
distance_between_markers_px0 = np.linalg.norm(points_nonaligned[0] - points_nonaligned[2])
distance_between_markers_px1 = np.linalg.norm(points_nonaligned[1] - points_nonaligned[3])
# distance_between_markers_px2 = np.sqrt((points_nonaligned[3, 0] - points_nonaligned[1, 0])**2 + (points_nonaligned[3, 1] - points_nonaligned[1, 1])**2)
distance_between_markers_px = (distance_between_markers_px0 + distance_between_markers_px1) / 2

mm_to_px = distance_between_markers_px/distance_between_markers_mm

R_45 = np.array([[0.70710678, -0.70710678], [0.70710678, 0.70710678]])
points_aligned0 = np.array([(0, distance_between_markers_mm/2), (distance_between_markers_mm/2, 0), (0, -distance_between_markers_mm/2), (-distance_between_markers_mm/2, 0)])
if rotate45:
    points_aligned  = points_aligned0 @ R_45 * mm_to_px + np.array([width/2, height/2]) 
else:
    points_aligned  = points_aligned0 * mm_to_px  + np.array([width/2, height/2]) 

# vertices_pxl = net.vertices_mm_to_pxl(net.vertices, mm_to_px, width, height)

print("Pixel locations:", points_nonaligned)
print("cordinate list:", points_aligned)

Pixel locations: [[3108.17451946 3402.56665778]
 [4642.92092255 1912.62638303]
 [3143.68243863  391.17704905]
 [1615.72692145 1880.52769267]]
cordinate list: [[3000.         3509.74077919]
 [4509.74077919 2000.        ]
 [3000.          490.25922081]
 [1490.25922081 2000.        ]]


In [9]:
homography_matrix, _ = cv2.findHomography(points_nonaligned, points_aligned, method=cv2.RANSAC)
aligned_image = cv2.warpPerspective(original_image, homography_matrix, (width, height))

points_aligned_validate = np.array([points_nonaligned[:, 0], points_nonaligned[:, 1], np.ones_like(points_nonaligned[:, 0])])
points_aligned_validate = np.dot(homography_matrix, points_aligned_validate)
points_aligned_validate = np.array([points_aligned_validate[0, :]/points_aligned_validate[2, :], points_aligned_validate[1, :]/points_aligned_validate[2, :]]).T

fig, ax = plt.subplots(1, 2, figsize=(15, 10), sharex=True, sharey=True)
ax[0].imshow(original_image)
ax[0].plot(points_nonaligned[:, 0], points_nonaligned[:, 1], 'r-*', markersize=10)
ax[0].plot(points_nonaligned[0, 0], points_nonaligned[0, 1], 'bo', markersize=10)
ax[0].set_title('Unaligned Image')
ax[0].axis('off')
ax[1].imshow(aligned_image)
ax[1].plot(points_aligned[:, 0], points_aligned[:, 1], 'r-*', markersize=10, label='known points')
ax[1].plot(points_aligned_validate[:, 0], points_aligned_validate[:, 1], 'g.', markersize=10, label='known points - validate')
ax[1].plot(points_aligned_validate[0, 0], points_aligned_validate[0, 1], 'bo', markersize=10, label='known points - validate')
ax[1].set_title('Orthogonal Image')
ax[1].axis('off')
plt.legend()

In [ ]:
points_checker_mm = net.vertices_pxl_to_mm(points_checker, mm_to_px, width, height)
points_checker_width0 = np.linalg.norm(points_checker_mm[0] - points_checker_mm[1])
points_checker_width1 = np.linalg.norm(points_checker_mm[2] - points_checker_mm[3])
points_checker_height0 = np.linalg.norm(points_checker_mm[0] - points_checker_mm[2])
points_checker_height1 = np.linalg.norm(points_checker_mm[1] - points_checker_mm[3])
print("Checkerboard width0:", points_checker_width0)
print("Checkerboard width1:", points_checker_width1)
print("Checkerboard height0:", points_checker_height0)
print("Checkerboard height1:", points_checker_height1)

# aligned_checker_image = cv2.warpPerspective(checker_image, homography_matrix, (width, height))

In [15]:
vertices_pxl = net.mm_to_px_using_homography(net.vertices_mm_to_pxl(net.vertices, mm_to_px, width, height), homography_matrix)
vertices_pxl_old = net.vertices_mm_to_pxl(net.vertices, mm_to_px, width, height)
vertices_pxl, vertices_pxl_old

(array([[1486.98347588,  740.59391419],
        [2497.10885361, 1711.73466019],
        [2920.78859772, 2098.82164189],
        [3305.24668877, 2527.94486701],
        [4257.96885529, 3463.42968826],
        [1520.00737482, 3498.61991664],
        [2494.50186357, 2547.90173932],
        [3286.36853102, 1712.08058318],
        [4226.30451273,  716.56425979]]),
 array([[1627.50837496,  627.50837496,    0.        ],
        [2625.54358879, 1603.9329701 ,    0.        ],
        [3045.36525042, 1994.24573415,    0.        ],
        [3425.90774002, 2426.59683857,    0.        ],
        [4372.49162504, 3372.49162504,    0.        ],
        [1627.50837496, 3372.49162504,    0.        ],
        [2613.04640993, 2437.23823329,    0.        ],
        [3416.52805704, 1612.32859895,    0.        ],
        [4372.49162504,  627.50837496,    0.        ]]))

In [17]:
points = []
fig, ax = plt.subplots(figsize=(15, 10))
ax.axis('off')
ax.set_aspect('equal')
ax.imshow(aligned_image)
# ax.imshow(original_image)
ax = net.net_plot_mat(ax, vlabels=True, fp=True, vertices_c = vertices_pxl)

circle = plt.Circle((0, 0), radius=4.88*mm_to_px, color='r', fill=False, lw=2)
ax.add_patch(circle)

fig.canvas.mpl_connect('button_press_event', on_click)
fig.canvas.mpl_connect('scroll_event', on_scroll)
fig.canvas.mpl_connect("motion_notify_event", on_motion2)
fig.canvas.mpl_connect('close_event', on_close)
ax.set_title('Click on the vertices of the network (in order). (Scroll to zoom)')
plt.show()

In [12]:
points = np.array(points)
points_mm = net.vertices_pxl_to_mm(points, mm_to_px, width, height)
points_mm, net.vertices

(array([[-65.8260504 ,  79.65965958],
        [-15.72361626,  27.29887419],
        [  5.95490148,   6.42326452],
        [ 25.75996707, -16.05816129],
        [ 77.94899125, -67.97954945],
        [-68.89462223, -68.58182186],
        [-16.2588883 , -16.32579731],
        [ 25.75996707,  25.96069408],
        [ 78.75189932,  76.54390214]]),
 array([[-70.71067812,  70.71067812,   0.        ],
        [-19.29196964,  20.40534729,   0.        ],
        [  2.33721471,   0.2964594 ,   0.        ],
        [ 21.94273871, -21.97824102,   0.        ],
        [ 70.71067812, -70.71067812,   0.        ],
        [-70.71067812, -70.71067812,   0.        ],
        [-19.93582347, -22.52648498,   0.        ],
        [ 21.45949806,  19.97280505,   0.        ],
        [ 70.71067812,  70.71067812,   0.        ]]))

In [13]:
file_path = os.path.join(BYU_UW_root, 'Tensile Testing', 'Avg_Stress_Strain_Overture_TPU_1mm2.csv')
stress_data, strain_data = net.load_stress_strain_curve(file_path)
strain_to_stress = net.material_model(stress_data, strain_data, interpolation_kind = 'cubic')
TPU_nl = {'stress':strain_data, 'strain': stress_data, 'v':0.3897, 'p':1.18e-9, 'A': 0.078294515, 'name': 'TPU Overture'} # TPU Overture non-conductive
A = [TPU_nl['A']]*len(net.edges)

vertices_equilibrium = np.copy(net.vertices)
vertices_equilibrium[net.fixed,:2] = points_mm[net.fixed]

vertices_equilibrium, l1_equilibrium, f = net.find_equilibrium(vertices_equilibrium, A, strain_to_stress)
vertices_equilibrium_pxl = net.vertices_mm_to_pxl(vertices_equilibrium, mm_to_px, width, height)
# net.net_plot(color=False, elables = True, vlabels = False, custom_vertices = vertices_equilibrium)
net.vertices, vertices_equilibrium

`ftol` termination condition is satisfied.


(array([[-70.71067812,  70.71067812,   0.        ],
        [-19.29196964,  20.40534729,   0.        ],
        [  2.33721471,   0.2964594 ,   0.        ],
        [ 21.94273871, -21.97824102,   0.        ],
        [ 70.71067812, -70.71067812,   0.        ],
        [-70.71067812, -70.71067812,   0.        ],
        [-19.93582347, -22.52648498,   0.        ],
        [ 21.45949806,  19.97280505,   0.        ],
        [ 70.71067812,  70.71067812,   0.        ]]),
 array([[-65.8260504 ,  79.65965958,   0.        ],
        [-19.37670746,  19.98351225,   0.        ],
        [  1.8558679 ,  -0.66851265,   0.        ],
        [ 21.65569932, -22.90120783,   0.        ],
        [ 77.94899125, -67.97954945,   0.        ],
        [-68.89462223, -68.58182186,   0.        ],
        [-20.46636084, -23.19379039,   0.        ],
        [ 21.30458401,  18.96567935,   0.        ],
        [ 78.75189932,  76.54390214,   0.        ]]))

In [14]:
# points = []
fig, ax = plt.subplots(figsize=(15, 10))
ax.axis('off')
ax.set_aspect('equal')
# ax.imshow(aligned_image)
ax.imshow(original_image)
ax = net.net_plot_mat(ax, vlabels=True, fp=True, vertices_c=vertices_equilibrium_pxl)
# ax = net.net_plot_mat(ax, vlabels=True, fp=True, vertices_c=vertices_pxl)
# ax.plot(vertices_pxl[net.fixed,0], vertices_pxl[net.fixed,1], 'b*', markersize=5, label='Fixed points - designed')
# ax.set_xlim(np.min(vertices_pxl[net.fixed,0]) - 100, np.max(vertices_pxl[net.fixed,0])+ 100)
# ax.set_ylim(np.max(vertices_pxl[net.fixed,1])+ 100, np.min(vertices_pxl[net.fixed,1])- 100)
ax.legend(fontsize=12)
plt.show()
# plt.savefig(os.path.join(BYU_UW_root, 'images','validation_images', model_name_im + '_val.png'), dpi=300, bbox_inches='tight')

Image window closed. `original_image` updated with final transformation.


In [ ]:
vertices_real = np.array(points)
# error_pixels = np.sqrt(np.sum((vertices_real - net.vertices[:, :2])**2, axis=1))
error_pixels = np.sqrt(np.sum((vertices_real - vertices_equilibrium[:, :2])**2, axis=1))
error_mm = error_pixels / mm_to_px
error_mm

In [ ]:
error_rel = 0
for edge_i, edge in enumerate(net.edges):
    coor0, coor1 = vertices_real[edge[0]], vertices_real[edge[1]]
    l1m = np.linalg.norm(coor0[:2] - coor1[:2])
    # error_rel += np.abs(l1m - net.l1[edge_i]) / net.l1[edge_i]
    error_rel += np.abs(l1m - l1_equilibrium[edge_i]) / l1_equilibrium[edge_i]
# error_rel /= distance_between_markers_mm
error_rel/ len(net.edges) # percentage error

In [ ]:
# net.vertices /= mm_to_px # Scale the network vertices to match the image scale
net.vertices -= np.array([width/2, height/2,0])

# Save the calibration results
calibration_results = {
    'model_name': model_name,
    'model_name_im': model_name_im,
    'camera_matrix': mtx,
    'distortion_coefficients': dist,
    'homography_matrix': homography_matrix,
    'real_vertices': points_mm,
    'equilibrium_vertices': vertices_equilibrium,
    'vertices': net.vertices,
    'error_pixels': error_pixels,
    'error_mm': error_mm,
    'error_rel': error_rel
}
np.save(os.path.join(BYU_UW_root, 'calibration_results', model_name_im + '_cr.npy'), calibration_results, allow_pickle=True)

model_name_im

In [ ]:
fig, ax = plt.subplots(1, 3, figsize=(15, 10), sharey=True)
ax[0].set_xlabel('Force (N)')
ax[1].set_xlabel('Curvature (1/m)')
ax[2].set_xlabel('Initial length (m)')
ax[0].set_ylabel('Relative error (%)')

calibration_results_files = glob.glob(os.path.join(BYU_UW_root, 'calibration_results', '*_cr.npy'))

for file in calibration_results_files:
    try:
        data = np.load(file, allow_pickle=True).item()
    except:
        print(f'for some reason {file} stopped working')
        continue
    model_name_im = data['model_name_im']
    model_name = data['model_name']
    real_vertices = data['real_vertices']
    vertices_equilibrium = data['equilibrium_vertices']

    print(model_name)
    try:
        net2 = Network_custom.load_network(os.path.join(BYU_UW_root, 'networks', model_name + '.pkl'))
    except:
        net2 = Network_custom.load_network(os.path.join(BYU_UW_root, 'networks', model_name + '_net.pkl')) 

    f = net2.f
    R = net2.R
    kappa = 1/R
    l0 = net2.l0
    error_edge = []
    for edge_i, edge in enumerate(net2.edges):
        coor0, coor1 = real_vertices[edge[0]], real_vertices[edge[1]]
        l1m = np.linalg.norm(coor0[:2] - coor1[:2])
        error_edge.append(np.abs(l1m - l1_equilibrium[edge_i]) / l1_equilibrium[edge_i])
    edge_error = np.array(error_edge) * 100 # percentage error
    ax[0].plot(f, error_edge, 'o', label=model_name_im)
    ax[1].plot(kappa, error_edge, 'o', label=model_name_im)
    ax[2].plot(l0, error_edge, 'o', label=model_name_im)

ax[0].legend()
ax[0].set_title('Force vs Relative Error')
ax[1].set_title('Curvature vs Relative Error')
ax[2].set_title('Initial Length vs Relative Error')
plt.tight_layout()
plt.show()

    